from __future__ import annotations


NUMERIC_FEATURES = [
    "LotFrontage",
    "LotArea",
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "1stFlrSF",
    "2ndFlrSF",
    "LowQualFinSF",
    "GrLivArea",
    "BsmtFullBath",
    "BsmtHalfBath",
    "FullBath",
    "HalfBath",
    "BedroomAbvGr",
    "KitchenAbvGr",
    "TotRmsAbvGrd",
    "Fireplaces",
    "GarageYrBlt",
    "GarageCars",
    "GarageArea",
    "WoodDeckSF",
    "OpenPorchSF",
    "EnclosedPorch",
    "3SsnPorch",
    "ScreenPorch",
    "PoolArea",
    "MiscVal",
    "MoSold",
    "YrSold",
    "YearBuilt",
    "YearRemodAdd",
]

CATEGORICAL_FEATURES = [
    "MSSubClass",
    "MSZoning",
    "Alley",
    "LandContour",
    "LotConfig",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "Foundation",
    "Heating",
    "Electrical",
    "GarageType",
    "MiscFeature",
    "SaleType",
    "SaleCondition",
]

ORDINAL_FEATURES = [
    "Street",
    "LotShape",
    "Utilities",
    "LandSlope",
    "ExterQual",
    "ExterCond",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "HeatingQC",
    "CentralAir",
    "KitchenQual",
    "Functional",
    "FireplaceQu",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PavedDrive",
    "PoolQC",
    "Fence",
]

LOG_TRANSFORM_COLUMNS = [
    "LotFrontage",
    "LotArea",
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "1stFlrSF",
    "2ndFlrSF",
    "GrLivArea",
    # "GarageArea",
    "WoodDeckSF",
    "OpenPorchSF",
    "EnclosedPorch",
    "ScreenPorch",
    "MiscVal",
]

FEATURE_GROUPS: dict[str, list[str]] = {
    "numeric_all": NUMERIC_FEATURES,
    "numeric_core": [
        "LotArea",
        "TotalBsmtSF",
        "1stFlrSF",
        "2ndFlrSF",
        "GrLivArea",
        "FullBath",
        "HalfBath",
        "TotRmsAbvGrd",
        "Fireplaces",
        "GarageCars",
        "GarageArea",
        "YearBuilt",
        "YearRemodAdd",
    ],
    "numeric_sparse_tail": [
        "LowQualFinSF",
        "3SsnPorch",
        "ScreenPorch",
        "PoolArea",
        "MiscVal",
    ],
    "ordinal_all": ORDINAL_FEATURES,
    "ordinal_core": [
        "LotShape",
        "ExterQual",
        "BsmtQual",
        "HeatingQC",
        "KitchenQual",
        "Functional",
        "GarageFinish",
        "PavedDrive",
    ],
    "categorical_all": CATEGORICAL_FEATURES,
    "categorical_core": [
        "Neighborhood",
        "MSZoning",
        "BldgType",
        "HouseStyle",
        "Foundation",
        "GarageType",
        "SaleCondition",
    ],
}
